name: osama_core
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  dashed_line: ^0.1.0+3
  equatable: ^2.0.5
  faker: ^2.2.0
  flash: ^3.1.1
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_localization: ^0.2.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  intl: ^0.20.2
  lottie: ^3.1.2
  pull_to_refresh:
    git:
      url: https://github.com/AhmadAmr/flutter_pulltorefresh.git
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^31.1.21
  syncfusion_flutter_core: ^31.1.21
  syncfusion_flutter_sliders: ^31.1.21
  tab_indicator_styler: ^2.0.0
  timelines_plus: ^1.0.4
  url_launcher: ^6.3.0
  # *****
  fluttertoast: ^8.2.10
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  uuid: ^4.4.2
  # appinio_social_share: ^0.3.2
  # appinio_social_share:
  #   git:
  #     url: https://github.com/orkun1675/appinio_flutter_packages.git
  #     path: packages/appinio_social_share


  # appinio_social_share:
  #   git:
  #     url: https://github.com/xhw0525/flutter_packages.git
  #     path: packages/appinio_social_share

  # social_share:
  #   git:
  #     url: https://github.com/midoandev/social_share.git
  flutter_inappwebview: ^6.1.5
  flutter_staggered_animations: ^1.1.1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.5

#   network_manager:
#     path: /Users/osamaabdelaziz/sak_company/network_manager/

  # network_manager:
  #   path: /Users/sak/Documents/apps/sak_company/network_manager/

  network_manager:
    git:
      url: https://github.com/Osama23/network_manager.git
      ref: master
#        //https://github.com/GetSakk/network_manager.git
#      ref: releases/dev


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.

# flutter_intl:
#   enabled: true
flutter:
  generate: true # Add this line
# To add assets to your package, add an assets section, like this:
assets:
  - assets/lottie/
  - assets/images/
  - assets/svg/
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://f